using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Data.Entity;

namespace EventStore.Models
{
	public class SampleData : DropCreateDatabaseAlways<EventStoreDB>
    {
        protected override void Seed(EventStoreDB context)
        {
            var types = new List<EventType>
            {
                new EventType {Type = "Concert"},
                new EventType { Type = "Meeting" },
                new EventType { Type = "Sports/Fitness" },
                new EventType { Type = "Game" },
                new EventType { Type = "Rally" },
                new EventType { Type = "Fundraiser" },
                new EventType { Type = "Autographs" },
                new EventType { Type = "Audition" },
                new EventType { Type = "Movie Screening" },
                new EventType { Type = "Market" },

            };

            new List<Event>
            {
                new Event { Title = "Shaggy and the Crew Live", Type = types.Single(g => g.Type == "Concert"), Description = "A live performance by Shaggy and the Crew.", StartDate = new DateTime(2019, 7, 22, 13, 0, 0), EndDate = new DateTime(2019, 7, 22, 16, 0, 0), Organizer = "Jerland Records", ContactInfo = "216-555-3457", City = "Ashland", State = "Ohio", MaxTickets = 400, AvailTickets = 400  },
                new Event { Title = ".Net Programmers Meetup", Type = types.Single(g => g.Type == "Meeting"), Description = "Come and meet other programmers working with .net.", StartDate = new DateTime(2019, 3, 10, 15, 0, 0), EndDate = new DateTime(2019, 3, 10, 17, 0, 0), Organizer = "Ace Gayheart", ContactInfo = "216-555-3759", City = "Cleveland", State = "Ohio", MaxTickets = 50, AvailTickets = 50  },
                new Event { Title = "Grant City Charity Marathon", Type = types.Single(g => g.Type == "Sports/Fitness"), Description = "Run a marathon to raise money for charity.", StartDate = new DateTime(2019, 7, 19, 7, 0, 0), EndDate = new DateTime(2019, 7, 19, 12, 0, 0), Organizer = "Sacred Heart Foundation", ContactInfo = "216-555-9455", City = "Grant City", State = "Nevada", MaxTickets = 200, AvailTickets = 200  },
                new Event { Title = "Let's Make a Deal Sharberton", Type = types.Single(g => g.Type == "Game"), Description = "Gather for a night of fun and giveaways.", StartDate = new DateTime(2019, 4, 15, 15, 0, 0), EndDate = new DateTime(2019, 4, 15, 18, 0, 0), Organizer = "Sharberton City Hall", ContactInfo = "216-555-9945", City = "Sharberton", State = "Wyoming", MaxTickets = 100, AvailTickets = 100  },
                new Event { Title = "Clint Forrester Election Rally", Type = types.Single(g => g.Type == "Rally"), Description = "Come and show your support for Senate candidate Clint Forrester.", StartDate = new DateTime(2019, 8, 20, 10, 30, 0), EndDate = new DateTime(2019, 8, 20, 13, 0, 0), Organizer = "Clint Forrester PAC", ContactInfo = "forresterforsenate@email.com", City = "Johnsonville", State = "Alabama", MaxTickets = 400, AvailTickets = 400  },
                new Event { Title = "Parma Scouts Fundraising Event", Type = types.Single(g => g.Type == "Fundraiser"), Description = "Help raise money for the local Scouts.", StartDate = new DateTime(2019, 5, 5, 13, 0, 0), EndDate = new DateTime(2019, 5, 5, 17, 0, 0), Organizer = "Parma Scouts", ContactInfo = "216-555-6911", City = "Parma", State = "Ohio", MaxTickets = 80, AvailTickets = 80  },
                new Event { Title = "Shaggy and the Crew Autographs", Type = types.Single(g => g.Type == "Autographs"), Description = "Come meet the talent behind 'Shaggy and the Crew' and get an autograph.", StartDate = new DateTime(2019, 7, 23, 10, 0, 0), EndDate = new DateTime(2019, 7, 23, 13, 0, 0), Organizer = "Jerland Records", ContactInfo = "216-555-3457", City = "Cleveland", State = "Ohio", MaxTickets = 100, AvailTickets = 100  },
                new Event { Title = "Pirates of Penzance audition", Type = types.Single(g => g.Type == "Audition"), Description = "Open auditions for Pirates of Penzance", StartDate = new DateTime(2019, 7, 22, 13, 0, 0), EndDate = new DateTime(2019, 7, 22, 16, 0, 0), Organizer = "Jerland Records", ContactInfo = "216-555-3457", City = "Cleveland", State = "Ohio", MaxTickets = 400, AvailTickets = 400  },
                new Event { Title = "'Argento' Premiere", Type = types.Single(g => g.Type == "Movie Screening"), Description = "Premiere of Independent film 'Argento'.", StartDate = new DateTime(2019, 9, 10, 17, 0, 0), EndDate = new DateTime(2019, 9, 10, 19, 30, 0), Organizer = "Sandusky Film Festival", ContactInfo = "sanfilmfest@email.com", City = "Sandusky", State = "Ohio", MaxTickets = 150, AvailTickets = 150  },
                new Event { Title = "Theronville Flea Market", Type = types.Single(g => g.Type == "Market"), Description = "Flea Market for Theronville sellers and buyers.", StartDate = new DateTime(2019, 6, 7, 9, 0, 0), EndDate = new DateTime(2019, 6, 7, 16, 0, 0), Organizer = "Theronville City Hall", ContactInfo = "216-555-4487", City = "Theronville", State = "Illinois", MaxTickets = 300, AvailTickets = 300  },
                new Event { Title = "Auradeth Live", Type = types.Single(g => g.Type == "Concert"), Description = "A live performance by Auradeth.", StartDate = new DateTime(2019, 10, 11, 13, 0, 0), EndDate = new DateTime(2019, 10, 11, 16, 0, 0), Organizer = "Cynthea Records", ContactInfo = "216-555-1133", City = "Pacifica", State = "New York", MaxTickets = 400, AvailTickets = 400  },
                new Event { Title = "Matt Smith Cancer Treatment Fundraiser", Type = types.Single(g => g.Type == "Fundraiser"), Description = "Help raise money for Matt's cancer treatment.", StartDate = new DateTime(2019, 1, 6, 12, 0, 0), EndDate = new DateTime(2019, 1, 6, 14, 0, 0), Organizer = "Charlotte Smith", ContactInfo = "216-555-7845", City = "Deerpark", State = "Nebraska", MaxTickets = 80, AvailTickets = 80  },
                new Event { Title = "Hunters Unite", Type = types.Single(g => g.Type == "Meeting"), Description = "Hunter meetup.", StartDate = new DateTime(2020, 4, 20, 11, 0, 0), EndDate = new DateTime(2020, 4, 20, 13, 0, 0), Organizer = "Hunters of Petersburg", ContactInfo = "216-555-2547", City = "Petersburg", State = "Pennsylvania", MaxTickets = 70, AvailTickets = 70  },
                new Event { Title = "Chevy Commercial Tryouts", Type = types.Single(g => g.Type == "Audition"), Description = "Try out to star in the next chevy commercial.", StartDate = new DateTime(2018, 7, 22, 13, 0, 0), EndDate = new DateTime(2018, 7, 22, 16, 0, 0), Organizer = "Chevrolet", ContactInfo = "contactchevrolet@email.com", City = "Resident City", State = "Alabama", MaxTickets = 1000, AvailTickets = 1000  },
                new Event { Title = "Matt Smith Cancer Treatment Fundraiser", Type = types.Single(g => g.Type == "Fundraiser"), Description = "Help raise money for Matt's cancer treatment.", StartDate = new DateTime(2019, 3, 6, 12, 0, 0), EndDate = new DateTime(2019, 3, 6, 14, 0, 0), Organizer = "Charlotte Smith", ContactInfo = "216-555-7845", City = "Deerpark", State = "Nebraska", MaxTickets = 80, AvailTickets = 80  },
                new Event { Title = "Matt Smith Cancer Treatment Fundraiser", Type = types.Single(g => g.Type == "Game"), Description = "Help raise money for Matt's cancer treatment.", StartDate = new DateTime(2019, 11, 21, 12, 0, 0), EndDate = new DateTime(2019, 11, 21, 14, 0, 0), Organizer = "Charlotte Smith", ContactInfo = "216-555-7845", City = "Deerpark", State = "Nebraska", MaxTickets = 80, AvailTickets = 80  },
                new Event { Title = "Matt Smith Cancer Treatment Fundraiser", Type = types.Single(g => g.Type == "Movie Screening"), Description = "Help raise money for Matt's cancer treatment.", StartDate = new DateTime(2019, 5, 6, 12, 0, 0), EndDate = new DateTime(2019, 5, 6, 14, 0, 0), Organizer = "Charlotte Smith", ContactInfo = "216-555-7845", City = "Deerpark", State = "Nebraska", MaxTickets = 80, AvailTickets = 80  },
                new Event { Title = "Matt Smith Cancer Treatment Fundraiser", Type = types.Single(g => g.Type == "Sports/Fitness"), Description = "Help raise money for Matt's cancer treatment.", StartDate = new DateTime(2019, 12, 24, 12, 0, 0), EndDate = new DateTime(2019, 12, 24, 14, 0, 0), Organizer = "Charlotte Smith", ContactInfo = "216-555-7845", City = "Deerpark", State = "Nebraska", MaxTickets = 80, AvailTickets = 80  },
                new Event { Title = "Matt Smith Cancer Treatment Fundraiser", Type = types.Single(g => g.Type == "Rally"), Description = "Help raise money for Matt's cancer treatment.", StartDate = new DateTime(2019, 5, 1, 12, 0, 0), EndDate = new DateTime(2019, 5, 1, 14, 0, 0), Organizer = "Charlotte Smith", ContactInfo = "216-555-7845", City = "Deerpark", State = "Nebraska", MaxTickets = 80, AvailTickets = 80  },
                new Event { Title = "Matt Smith Cancer Treatment Fundraiser", Type = types.Single(g => g.Type == "Autographs"), Description = "Help raise money for Matt's cancer treatment.", StartDate = new DateTime(2019, 4, 26, 12, 0, 0), EndDate = new DateTime(2019, 4, 26, 14, 0, 0), Organizer = "Charlotte Smith", ContactInfo = "216-555-7845", City = "Deerpark", State = "Nebraska", MaxTickets = 80, AvailTickets = 80  },
                new Event { Title = "Matt Smith Cancer Treatment Fundraiser", Type = types.Single(g => g.Type == "Fundraiser"), Description = "Help raise money for Matt's cancer treatment.", StartDate = new DateTime(2019, 10, 23, 12, 0, 0), EndDate = new DateTime(2019, 10, 23, 14, 0, 0), Organizer = "Charlotte Smith", ContactInfo = "216-555-7845", City = "Deerpark", State = "Nebraska", MaxTickets = 80, AvailTickets = 80  },
                new Event { Title = "Matt Smith Cancer Treatment Fundraiser", Type = types.Single(g => g.Type == "Concert"), Description = "Help raise money for Matt's cancer treatment.", StartDate = new DateTime(2019, 6, 19, 12, 0, 0), EndDate = new DateTime(2019, 6, 19, 14, 0, 0), Organizer = "Charlotte Smith", ContactInfo = "216-555-7845", City = "Deerpark", State = "Nebraska", MaxTickets = 80, AvailTickets = 80  },
                new Event { Title = "Matt Smith Cancer Treatment Fundraiser", Type = types.Single(g => g.Type == "Fundraiser"), Description = "Help raise money for Matt's cancer treatment.", StartDate = new DateTime(2019, 5, 5, 12, 0, 0), EndDate = new DateTime(2019, 5, 5, 14, 0, 0), Organizer = "Charlotte Smith", ContactInfo = "216-555-7845", City = "Deerpark", State = "Nebraska", MaxTickets = 80, AvailTickets = 80  },
                new Event { Title = "Matt Smith Cancer Treatment Fundraiser", Type = types.Single(g => g.Type == "Movie Screening"), Description = "Help raise money for Matt's cancer treatment.", StartDate = new DateTime(2019, 9, 1, 12, 0, 0), EndDate = new DateTime(2019, 9, 1, 14, 0, 0), Organizer = "Charlotte Smith", ContactInfo = "216-555-7845", City = "Deerpark", State = "Nebraska", MaxTickets = 80, AvailTickets = 80  },
                new Event { Title = "Matt Smith Cancer Treatment Fundraiser", Type = types.Single(g => g.Type == "Fundraiser"), Description = "Help raise money for Matt's cancer treatment.", StartDate = new DateTime(2019, 7, 6, 12, 0, 0), EndDate = new DateTime(2019, 7, 6, 14, 0, 0), Organizer = "Charlotte Smith", ContactInfo = "216-555-7845", City = "Deerpark", State = "Nebraska", MaxTickets = 80, AvailTickets = 80  },
                new Event { Title = "Matt Smith Cancer Treatment Fundraiser", Type = types.Single(g => g.Type == "Sports/Fitness"), Description = "Help raise money for Matt's cancer treatment.", StartDate = new DateTime(2019, 2, 17, 12, 0, 0), EndDate = new DateTime(2019, 2, 17, 14, 0, 0), Organizer = "Charlotte Smith", ContactInfo = "216-555-7845", City = "Deerpark", State = "Nebraska", MaxTickets = 80, AvailTickets = 80  },
                new Event { Title = "Matt Smith Cancer Treatment Fundraiser", Type = types.Single(g => g.Type == "Fundraiser"), Description = "Help raise money for Matt's cancer treatment.", StartDate = new DateTime(2019, 3, 5, 12, 0, 0), EndDate = new DateTime(2019, 3, 5, 14, 0, 0), Organizer = "Charlotte Smith", ContactInfo = "216-555-7845", City = "Deerpark", State = "Nebraska", MaxTickets = 80, AvailTickets = 80  },
                new Event { Title = "Matt Smith Cancer Treatment Fundraiser", Type = types.Single(g => g.Type == "Meeting"), Description = "Help raise money for Matt's cancer treatment.", StartDate = new DateTime(2019, 8, 30, 12, 0, 0), EndDate = new DateTime(2019, 8, 30, 14, 0, 0), Organizer = "Charlotte Smith", ContactInfo = "216-555-7845", City = "Deerpark", State = "Nebraska", MaxTickets = 80, AvailTickets = 80  },
                new Event { Title = "Matt Smith Cancer Treatment Fundraiser", Type = types.Single(g => g.Type == "Market"), Description = "Help raise money for Matt's cancer treatment.", StartDate = new DateTime(2021, 1, 6, 12, 0, 0), EndDate = new DateTime(2021, 1, 6, 14, 0, 0), Organizer = "Charlotte Smith", ContactInfo = "216-555-7845", City = "Deerpark", State = "Nebraska", MaxTickets = 80, AvailTickets = 80  },
                new Event { Title = "Matt Smith Cancer Treatment Fundraiser", Type = types.Single(g => g.Type == "Rally"), Description = "Help raise money for Matt's cancer treatment.", StartDate = new DateTime(2019, 5, 4, 12, 0, 0), EndDate = new DateTime(2019, 5, 4, 14, 0, 0), Organizer = "Charlotte Smith", ContactInfo = "216-555-7845", City = "Deerpark", State = "Nebraska", MaxTickets = 80, AvailTickets = 80  }


            }.ForEach(a => context.Events.Add(a));
        }
    }
}